### ISSUE TITLE
Few bugs with the API

### ISSUE THREAD

**Issue by topwebstudio** [ultramsg/whatsapp-php-sdk#13]
Hey there I'm working with your API and I have discovered few inconsistencies. 

1) sendInstanceSettings() is not taking into account any changes and actually resets all fields to the default values 
2) no data is posted to webhook_url (I've set the URL manually through the website control panel because the above bug) 

So when action is received I get no $_POST  or $_GET data (the URL has been called but no data is available)

**Comment by ultramsg** [comment]
Thank you for reaching out and for sharing your observations about the API behavior. Based on our review, it appears that the issues you're encountering with sendInstanceSettings() and webhook_url may stem from usage configurations rather than a system issue on our side.


To help resolve this, we recommend reviewing the setup and ensuring that the fields are configured according to the API guidelines. If you need further assistance, please feel free to reach out to our support team, who can guide you through the process and answer any questions.

Thank you for your understanding, and we’re here to support you with any additional queries.

Best regards,
